### ISSUE TITLE
Interested in the 'original fork'?

### ISSUE THREAD

**Issue by gavanderhoorn** [dbenders1/rotors_simulator_wind_plugin#1]
I believe [gavanderhoorn/rotors_simulator](https://github.com/gavanderhoorn/rotors_simulator) is the fork of `rotors_simulator` in which I did the original pruning.

As that includes the original repository history and doesn't copy any files, you could use that instead of the copy in this repository.

Let me know if you'd like me to transfer that fork to you.

**Comment by dbenders1** [comment]
Yes that would be nice. Thank you.

**Comment by gavanderhoorn** [comment]
Done.
